/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectrmi;

import java.awt.Color;
import java.awt.Dimension;
import java.rmi.Naming;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author melid
 */
public class ClientFrame extends javax.swing.JFrame {

    /**
     * Creates new form ClientFrame
     */
    String ChoosenFood;
     JButton [] buttoni=new JButton[6];
     String [] nizOrder;
     public int prebroj;
     public Interface fo;
    public ClientFrame() {
        initComponents();
        kreirajMeni();
        JButton b=new JButton("Klikni");
        JPanel panel=new JPanel();
        panel.setBackground(Color.yellow);
        b.setPreferredSize(new Dimension(50,50));
       // b.setText("BLA");
       panel.add(b);
    //   this.jPanel1.add(panel);
    this.getContentPane().add(panel);
        setVisible(true);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
     // validate();
        
       
    }
  
    public void kreirajMeni()
    {
        
        
        String [] nizMenu;
      //  String [] nizOrder;
        buttoni[0]=this.btnBurger;
        buttoni[1]=this.btnPizza;
        buttoni[2]=this.btnFish;
        buttoni[3]=this.btnNacos;
        buttoni[4]=this.btnSushi;
        buttoni[5]=this.btnFries;
       
         try
           {
            fo = (Interface)Naming.lookup("//localhost/burger");
            //FoodOrderInterface fo1 = (FoodOrderInterface)Naming.lookup("//localhost/pizza");
       
            nizMenu=new String[fo.getMenu().length];
            nizMenu=fo.getMenu();
            for(int i=0;i<nizMenu.length;i++){
                buttoni[i].setText(nizMenu[i]);
            }           
             // izabranaPoruzbina();
            
             
                       
            }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
        
        
    }
    public void HandlerEventFood(JButton b)
   {
       this.ChoosenFood=b.getText();
       this.txtPorudzbina.setText(this.txtPorudzbina.getText()+" "+b.getText()+"\n");
      
       
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        btnBurger = new javax.swing.JButton();
        btnFries = new javax.swing.JButton();
        btnFish = new javax.swing.JButton();
        btnNacos = new javax.swing.JButton();
        btnSushi = new javax.swing.JButton();
        btnPizza = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPorudzbina = new javax.swing.JTextArea();
        btnPoruci = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtRacun = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(164, 198, 57));

        jTabbedPane2.setBackground(new java.awt.Color(164, 198, 57));
        jTabbedPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTabbedPane2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(248, 235, 216));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBurger.setBackground(new java.awt.Color(252, 203, 26));
        btnBurger.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnBurger.setForeground(new java.awt.Color(255, 255, 255));
        btnBurger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBurgerbtnChoosenFoodHandler(evt);
            }
        });
        btnBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBurgerActionPerformed(evt);
            }
        });
        jPanel2.add(btnBurger, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 130));

        btnFries.setBackground(new java.awt.Color(252, 203, 26));
        btnFries.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnFries.setForeground(new java.awt.Color(255, 255, 255));
        btnFries.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFriesChoosenFoodHandler(evt);
            }
        });
        jPanel2.add(btnFries, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 160, 130));

        btnFish.setBackground(new java.awt.Color(252, 203, 26));
        btnFish.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnFish.setForeground(new java.awt.Color(255, 255, 255));
        btnFish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFishChoosenFoodHandler(evt);
            }
        });
        jPanel2.add(btnFish, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 160, 130));

        btnNacos.setBackground(new java.awt.Color(252, 203, 26));
        btnNacos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnNacos.setForeground(new java.awt.Color(255, 255, 255));
        btnNacos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNacosChoosenFoodHandler(evt);
            }
        });
        jPanel2.add(btnNacos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 160, 130));

        btnSushi.setBackground(new java.awt.Color(252, 203, 26));
        btnSushi.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnSushi.setForeground(new java.awt.Color(255, 255, 255));
        btnSushi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSushiChoosenFoodHandler(evt);
            }
        });
        jPanel2.add(btnSushi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 160, 130));

        btnPizza.setBackground(new java.awt.Color(252, 203, 26));
        btnPizza.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnPizza.setForeground(new java.awt.Color(255, 255, 255));
        btnPizza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPizzaChoosenFoodHandler(evt);
            }
        });
        jPanel2.add(btnPizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 160, 130));

        jTabbedPane2.addTab("Food", jPanel2);

        txtPorudzbina.setColumns(20);
        txtPorudzbina.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtPorudzbina.setRows(5);
        jScrollPane1.setViewportView(txtPorudzbina);

        btnPoruci.setBackground(new java.awt.Color(164, 198, 57));
        btnPoruci.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnPoruci.setForeground(new java.awt.Color(255, 255, 255));
        btnPoruci.setText("ORDER");
        btnPoruci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPoruciActionPerformed(evt);
            }
        });

        txtRacun.setColumns(20);
        txtRacun.setRows(5);
        jScrollPane2.setViewportView(txtRacun);

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("List of orders");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Receipt");

        jPanel4.setBackground(new java.awt.Color(141, 170, 49));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnPoruci, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(btnPoruci, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPoruciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoruciActionPerformed
        // TODO add your handling code here:
        prebroj=this.txtPorudzbina.getLineCount()-1;
        System.out.println(prebroj);
         if(this.txtPorudzbina.getText().isEmpty()==true)
        {
            JOptionPane.showMessageDialog(this, "You didn't choose");
        }
         else{
                String []bla=new String[prebroj];
                bla=this.txtPorudzbina.getText().split("\n");
           
                System.out.println(bla[0]+bla[1]);
            try {
                for(int i=0;i<bla.length;i++)
                fo.setOrder(bla[i], i);
            } catch (RemoteException ex) {
                Logger.getLogger(ClientFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
                /*for(int i=0;i<=bla.length;i++){
                     System.out.println(bla[i]);
                   //  this.nizOrder[i]=bla[i];
                     try {
                     
                       
            } catch (RemoteException ex) {
                Logger.getLogger(ClientFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
               
                }*/
             
                  try {
                     String [] g=fo.getOrder();
                   
                     for(int i=0;i<prebroj;i++)
                     {
                         String izabrao=g[i];
                         this.txtRacun.setText(izabrao+this.txtRacun.getText()+"\n");
                           System.out.println("POSLO SAM "+g[i]);
                         //this.txtRacun.setText(this.txtRacun.getText()+g[i]+"\n");
                         
                         
                         
                     }
                     JOptionPane.showMessageDialog(this, "Porudzbina je poslata");
                     System.exit(0);
                 } catch (RemoteException ex) {
                     Logger.getLogger(ClientFrame.class.getName()).log(Level.SEVERE, null, ex);
                 }
                
                       
         }
          
    }//GEN-LAST:event_btnPoruciActionPerformed

    private void btnPizzaChoosenFoodHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPizzaChoosenFoodHandler
        // TODO add your handling code here:
        HandlerEventFood((JButton)evt.getSource());
    }//GEN-LAST:event_btnPizzaChoosenFoodHandler

    private void btnSushiChoosenFoodHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSushiChoosenFoodHandler

        // TODO add your handling code here:
        HandlerEventFood((JButton)evt.getSource());
    }//GEN-LAST:event_btnSushiChoosenFoodHandler

    private void btnNacosChoosenFoodHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNacosChoosenFoodHandler

        // TODO add your handling code here:
        HandlerEventFood((JButton)evt.getSource());
    }//GEN-LAST:event_btnNacosChoosenFoodHandler

    private void btnFishChoosenFoodHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFishChoosenFoodHandler

        // TODO add your handling code here:
        HandlerEventFood((JButton)evt.getSource());
    }//GEN-LAST:event_btnFishChoosenFoodHandler

    private void btnFriesChoosenFoodHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFriesChoosenFoodHandler

        // TODO add your handling code here:
        HandlerEventFood((JButton)evt.getSource());
    }//GEN-LAST:event_btnFriesChoosenFoodHandler

    private void btnBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBurgerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBurgerActionPerformed

    private void btnBurgerbtnChoosenFoodHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBurgerbtnChoosenFoodHandler
        // TODO add your handling code here:
        HandlerEventFood((JButton)evt.getSource());
    }//GEN-LAST:event_btnBurgerbtnChoosenFoodHandler

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               ClientFrame f= new ClientFrame();
//               JButton b=new JButton();
//               JPanel panel=new JPanel();
//               panel.add(b);
//               b.setPreferredSize(new Dimension(50,50));
//              // f.add(b);
//               f.getContentPane().add(panel);
//               f.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBurger;
    private javax.swing.JButton btnFish;
    private javax.swing.JButton btnFries;
    private javax.swing.JButton btnNacos;
    private javax.swing.JButton btnPizza;
    private javax.swing.JButton btnPoruci;
    private javax.swing.JButton btnSushi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea txtPorudzbina;
    private javax.swing.JTextArea txtRacun;
    // End of variables declaration//GEN-END:variables
}
